version: "3.9"


services:
  loadbalancer:
      build:  .
      container_name: loadbalancer
      ports:
        - "5000:5000"
      privileged: true
      networks:
          net1:
             aliases:
                - loadbalancer
      volumes: 
          - /var/run/docker.sock:/var/run/docker.sock


networks:
   net1:
